[package]
name = "bitcoind-rpc-unavailable"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
tempfile = "3.3.0"
bitcoincore-rpc = "0.15.0"
env_logger = "0.9.0"

[dependencies.bdk]
version = "0.20.0"
features = ["rpc", "keys-bip39", "sqlite"]
